// Generated by CoffeeScript 1.6.3
var FilterCards, Init, RenderCardInfo, RenderFilterOptions, RenderMain, ResetFilters, cardNameUniqList, dbFiltered, dbUrl, dbZXCard;

dbUrl = "http://zx.colintrinity.com/";

dbFiltered = void 0;

dbZXCard = new Array();

cardNameUniqList = void 0;

$(document).ready(function() {
  _.each(dbMain, function(value, key) {
    return dbZXCard.push(_.extend(value, {
      Id: key
    }));
  });
  return Init();
});

RenderFilterOptions = function() {
  var cardColorList, cardCostList, cardIconList, cardPowerList, cardRaceList, cardRarityList, cardSetList, cardTagList, cardTypeList;
  cardTypeList = _.chain(dbZXCard).pluck("Type").uniq().compact().without("-").without("－").value();
  $(".filter-types").children().remove();
  _.each(cardTypeList, function(type) {
    return $(".filter-types").append("<option value='" + type + "'>" + type + "</option>");
  });
  if (cardTypeList.length < 1) {
    $(".filter-types").prop("disabled", true);
  } else {
    $(".filter-types").prepend("<option value=''>(All)</option>");
  }
  cardColorList = _.chain(dbZXCard).pluck("CardColor_Ch").uniq().compact().without("-").without("－").value();
  $(".filter-colors").children().remove();
  _.each(cardColorList, function(color) {
    return $(".filter-colors").append("<label class='btn btn-primary btn-xs'><input type='checkbox' value='" + color + "'>" + color + "</label>");
  });
  cardCostList = _.chain(dbZXCard).pluck("Cost").uniq().compact().without("-").without("－").sortBy(function(cost) {
    return parseInt(cost);
  }).value();
  $(".filter-costs").children().remove();
  _.each(cardCostList, function(cost) {
    return $(".filter-costs").append("<option>" + cost + "</option>");
  });
  if (cardCostList.length < 1) {
    $(".filter-cost-method").prop("disabled", true);
  } else {
    $(".filter-costs").prepend("<option value='-1'>(费用)</option>");
  }
  cardPowerList = _.chain(dbZXCard).pluck("Power").uniq().compact().without("-").without("－").sortBy(function(power) {
    return parseInt(power);
  }).value();
  $(".filter-powers").children().remove();
  _.each(cardPowerList, function(power) {
    return $(".filter-powers").append("<option>" + power + "</option>");
  });
  if (cardPowerList.length < 1) {
    $(".filter-power-method").prop("disabled", true);
  } else {
    $(".filter-powers").prepend("<option value='-1'>(力量)</option>");
  }
  cardIconList = _.chain(dbZXCard).pluck("Icon").uniq().compact().without("-").without("－").value();
  $(".filter-icons").children().remove();
  _.each(cardIconList, function(icon) {
    return $(".filter-icons").append("<option value='" + icon + "'>" + icon + "</option>");
  });
  if (cardIconList.length < 1) {
    $(".filter-icons").prop("disabled", true);
  } else {
    $(".filter-icons").prepend("<option value=''>(标记)</option>");
  }
  cardRaceList = _.chain(dbZXCard).pluck("Race").uniq().compact().without("-").without("－").value();
  $(".filter-races").children().remove();
  _.each(cardRaceList, function(race) {
    return $(".filter-races").append("<option value='" + race + "'>" + race + "</option>");
  });
  if (cardRaceList.length < 1) {
    $(".filter-races").prop("disabled", true);
  } else {
    $(".filter-races").prepend("<option value=''>(种族)</option>");
  }
  cardSetList = _.chain(dbZXCard).pluck("CardSet").uniq().compact().without("-").without("－").value();
  $(".filter-cardsets").children().remove();
  _.each(cardSetList, function(set) {
    return $(".filter-cardsets").append("<option value='" + set + "'>" + set + "</option>");
  });
  if (cardSetList.length < 1) {
    $(".filter-cardsets").prop("disabled", true);
  } else {
    $(".filter-cardsets").prepend("<option value=''>(卡包)</option>");
  }
  cardRarityList = _.chain(dbZXCard).pluck("Rarity").uniq().compact().without("-").without("－").value();
  $(".filter-rarities").children().remove();
  _.each(cardRarityList, function(rarity) {
    return $(".filter-rarities").append("<option value='" + rarity + "'>" + rarity + "</option>");
  });
  if (cardRarityList.length < 1) {
    $(".filter-rarities").prop("disabled", true);
  } else {
    $(".filter-rarities").prepend("<option value=''>(罕贵度)</option>");
  }
  cardTagList = _.chain(dbZXCard).pluck("Tag").uniq().compact().without("-").without("－").value();
  $(".filter-tags").children().remove();
  return _.each(cardTagList, function(tag) {
    return $(".filter-tags").append("<label class='btn btn-primary btn-xs'><input type='checkbox' value='" + tag + "'>" + tag + "</label>");
  });
};

Init = function() {
  cardNameUniqList = _.chain(dbZXCard).pluck("CardName_Ch").uniq().compact().without("-").without("－").value();
  $(".about-card-count").text(dbMain.length);
  RenderFilterOptions();
  $(".card-summary-details").click(function() {
    return window.open(dbUrl + encodeURIComponent($(this).data("card-name-jp")));
  });
  $(".btn-reset").click(function() {
    return ResetFilters();
  });
  $(".filter-keyword").on({
    change: function() {
      return FilterCards();
    },
    keyup: function() {
      return FilterCards();
    }
  });
  FilterCards();
  $(".filter-types").change(function() {
    return FilterCards();
  });
  $(".filter-colors input[type=checkbox]").change(function() {
    return FilterCards();
  });
  $(".filter-costs").change(function() {
    return FilterCards();
  });
  $(".filter-cost-method").change(function() {
    return FilterCards();
  });
  $(".filter-powers").change(function() {
    return FilterCards();
  });
  $(".filter-power-method").change(function() {
    return FilterCards();
  });
  $(".filter-icons").change(function() {
    return FilterCards();
  });
  $(".filter-races").change(function() {
    return FilterCards();
  });
  $(".filter-cardsets").change(function() {
    return FilterCards();
  });
  $(".filter-rarities").change(function() {
    return FilterCards();
  });
  $(".filter-tags input[type=checkbox]").change(function() {
    return FilterCards();
  });
  return $(".zx-card-tabs li").click(function() {
    var tabId;
    $(".zx-card-tabs li").removeClass("active");
    $(this).addClass("active");
    $(".zx-tab-pages div").hide();
    tabId = $(this).data("tab");
    $(".zx-tab-pages div[data-tab=" + tabId + "]").show();
  });
};

RenderMain = function(t) {
  var filter_result_container, i, _i, _ref;
  filter_result_container = $(".main-filter-result");
  filter_result_container.children().remove();
  for (i = _i = 0, _ref = dbFiltered.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    filter_result_container.append("<a data-id='" + dbFiltered[i].Id + "'><span>" + dbFiltered[i].CardName_Ch + "</span></a>");
  }
  $(".main-filter-result a").click(function() {
    var id;
    $(".card-summary-versions").children().remove();
    id = $(this).data("id");
    _.each(dbZXCard, function(value, key) {
      if (value.CardName_Ch === dbZXCard[id].CardName_Ch) {
        if (_.isNull(value.Version)) {
          value.Version = "";
        }
        $(".card-summary-versions").append("<option data-id='" + value.Id + "'>" + (value.SerialNo + value.Version) + "</option>");
      }
    });
    $(".card-summary-versions").change(function() {
      RenderCardInfo($(this).find("option:checked").data("id"));
    });
    return RenderCardInfo($(this).data("id"));
  });
  return $(".main-filter-result a:first-child").click();
};

RenderCardInfo = function(id) {
  var card_tags_container, classSuffix;
  $(".main-filter-result a.actived").removeClass("actived");
  $(".main-filter-result a[data-id=" + id + "]").addClass("actived");
  if (_.isNull(dbZXCard[id].Img_Suffix)) {
    dbZXCard[id].Img_Suffix = "";
  }
  $(".card-summary-image").css("background-image", "url(images/card-img/" + (dbZXCard[id].SerialNo + dbZXCard[id].Img_Suffix) + ".png)");
  $(".card-summary-illustrator").text(dbZXCard[id].Illustrator);
  $(".card-summary-details").data("card-name-jp", dbZXCard[id].CardName_Jp);
  $(".main-card-detail").attr("class", "main-card-detail col-lg-4 col-md-3");
  classSuffix = "";
  switch (dbZXCard[id].CardColor_Ch) {
    case "蓝":
      classSuffix = "blue";
      break;
    case "白":
      classSuffix = "white";
      break;
    case "黑":
      classSuffix = "black";
      break;
    case "绿":
      classSuffix = "green";
      break;
    case "红":
      classSuffix = "red";
      break;
    case "无":
      classSuffix = "mu";
      break;
    case "龙":
      classSuffix = "dragon";
  }
  $(".main-card-detail").addClass("card-color-" + classSuffix);
  card_tags_container = $(".card-detail-tags");
  card_tags_container.children().remove();
  card_tags_container.append("<span class='icon'></span>");
  card_tags_container.append("<span class='label label-default'>" + dbZXCard[id].SerialNo + "</span>");
  card_tags_container.append("<span class='label label-default'>" + dbZXCard[id].Rarity + "</span>");
  card_tags_container.append("<span class='label label-default'>" + dbZXCard[id].Race + "</span>");
  card_tags_container.append("<span class='label label-default'>" + dbZXCard[id].Type + "</span>");
  $(".card-detail-cardname-ch").text(dbZXCard[id].CardName_Ch);
  $(".card-detail-cardname-jp").text(dbZXCard[id].CardName_Jp);
  $(".card-detail-cost").text(dbZXCard[id].Cost);
  $(".card-detail-power").text(dbZXCard[id].Power);
  $(".card-detail-icon").attr("class", "card-detail-icon card-detail-fontsize-large");
  if (dbZXCard[id].Icon === "-" || "－") {
    $(".card-detail-icon").text("-");
  } else {
    $(".card-detail-icon").addClass("card-icon ");
    $(".card-detail-icon").addClass("icon-" + (dbZXCard[id].Icon.toLowerCase()));
  }
  $(".card-detail-ability-ch").text(dbZXCard[id].Ability_Ch);
  $(".card-description textarea").text(dbZXCard[id].Description_Ch);
  if (_.isNull(dbZXCard[id].Neta)) {
    dbZXCard[id].Neta = "";
  }
  $(".card-neta textarea").text(dbZXCard[id].Neta);
  if (_.isNull(dbZXCard[id].Ruling)) {
    dbZXCard[id].Ruling = "";
  }
  $(".card-ruling textarea").text(dbZXCard[id].Ruling);
};

ResetFilters = function() {
  $(".filter-keyword").val("");
  $(".filter-colors label").removeClass("active");
  $(".filter-colors input").prop("checked", false);
  $(".filter-types option:first-child").prop("selected", true);
  $(".filter-cost-method option:first-child").prop("selected", true);
  $(".filter-costs option:first-child").prop("selected", true);
  $(".filter-powers option:first-child").prop("selected", true);
  $(".filter-power-method option:first-child").prop("selected", true);
  $(".filter-icons option:first-child").prop("selected", true);
  $(".filter-races option:first-child").prop("selected", true);
  $(".filter-cardsets option:first-child").prop("selected", true);
  $(".filter-rarities option:first-child").prop("selected", true);
  $(".filter-tags label").removeClass("active");
  $(".filter-tags input").prop("checked", false);
  return FilterCards();
};

FilterCards = function() {
  var cardset, color, cost, icon, keyword, opt, power, race, rarity, tags, tmpUniqLst, type;
  dbFiltered = dbZXCard;
  keyword = $(".filter-keyword").val();
  type = $(".filter-types").val();
  color = _.pluck($(".filter-colors input:checked"), "value");
  icon = $(".filter-icons").val();
  race = $(".filter-races").val();
  cardset = $(".filter-cardsets").val();
  rarity = $(".filter-rarities").val();
  tags = _.pluck($(".filter-tags input:checked"), "value");
  cost = $(".filter-costs").val();
  power = $(".filter-powers").val();
  if (keyword.length !== 0) {
    dbFiltered = _.filter(dbFiltered, function(obj) {
      if ((obj.CardName_Ch != null) && obj.CardName_Ch.search(keyword) !== -1) {
        return true;
      } else if ((obj.CardName_Jp != null) && obj.CardName_Jp.search(keyword) !== -1) {
        return true;
      } else if ((obj.Nickname != null) && obj.Nickname.search(keyword) !== -1) {
        return true;
      } else {
        return false;
      }
    });
  }
  if (type.length !== 0) {
    dbFiltered = _.filter(dbFiltered, function(obj) {
      if (obj.Type.search(type) !== -1) {
        return true;
      } else {
        return false;
      }
    });
  }
  if (color.length !== 0) {
    dbFiltered = _.filter(dbFiltered, function(obj) {
      return _.contains(color, obj.CardColor_Ch);
    });
  }
  if (icon.length !== 0) {
    dbFiltered = _.filter(dbFiltered, function(obj) {
      if (obj.Icon.search(icon) !== -1) {
        return true;
      } else {
        return false;
      }
    });
  }
  if (race.length !== 0) {
    dbFiltered = _.filter(dbFiltered, function(obj) {
      if (obj.Race.search(race) !== -1) {
        return true;
      } else {
        return false;
      }
    });
  }
  if (cardset.length !== 0) {
    dbFiltered = _.filter(dbFiltered, function(obj) {
      if (obj.CardSet.search(cardset) !== -1) {
        return true;
      } else {
        return false;
      }
    });
  }
  if (rarity.length !== 0) {
    dbFiltered = _.filter(dbFiltered, function(obj) {
      if (obj.Rarity.search(rarity) !== -1) {
        return true;
      } else {
        return false;
      }
    });
  }
  if (tags.length !== 0) {
    dbFiltered = _.filter(dbFiltered, function(obj) {
      return _.contains(tags, obj.Tag);
    });
  }
  if (cost !== "-1") {
    opt = $(".filter-cost-method").val();
    dbFiltered = _.filter(dbFiltered, function(obj) {
      if (obj.Cost === "-" || "－") {
        false;
      }
      switch (opt) {
        case ">":
          return parseInt(obj.Cost) > parseInt(cost);
        case "=":
          return parseInt(obj.Cost) === parseInt(cost);
        case "<":
          return parseInt(obj.Cost) < parseInt(cost);
      }
    });
  }
  if (power !== "-1") {
    opt = $(".filter-power-method").val();
    dbFiltered = _.filter(dbFiltered, function(obj) {
      if (obj.Power === "-" || "－") {
        false;
      }
      switch (opt) {
        case ">":
          return parseInt(obj.Power) > parseInt(power);
        case "=":
          return parseInt(obj.Power) === parseInt(power);
        case "<":
          return parseInt(obj.Power) < parseInt(power);
      }
    });
  }
  tmpUniqLst = cardNameUniqList;
  dbFiltered = _.filter(dbFiltered, function(obj) {
    if (_.contains(tmpUniqLst, obj.CardName_Ch)) {
      tmpUniqLst = _.without(tmpUniqLst, obj.CardName_Ch);
      return true;
    } else {
      return false;
    }
  });
  RenderMain();
};
